CREATE TABLE KAFKA_MESSAGE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TOPIC VARCHAR(120) NOT NULL,
  BIZ_KEY VARCHAR(100)  NULL,
  MSG_HEADERS VARCHAR(200) NULL,
  MSG_KEY VARCHAR(200) NULL,
  MSG TEXT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIME
);

